/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AdjustItem from './AdjustItem';

/**
 * The AdjustRequest model module.
 * @module model/AdjustRequest
 * @version 5.0
 */
class AdjustRequest {
    /**
     * Constructs a new <code>AdjustRequest</code>.
     * Request needed for adjusting inventory
     * @alias module:model/AdjustRequest
     */
    constructor() { 
        
        AdjustRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AdjustRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AdjustRequest} obj Optional instance to populate.
     * @return {module:model/AdjustRequest} The populated <code>AdjustRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AdjustRequest();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [AdjustItem]);
            }
        }
        return obj;
    }


}

/**
 * List of items to adjust
 * @member {Array.<module:model/AdjustItem>} items
 */
AdjustRequest.prototype['items'] = undefined;






export default AdjustRequest;

