/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AdjustItem model module.
 * @module model/AdjustItem
 * @version 5.0
 */
class AdjustItem {
    /**
     * Constructs a new <code>AdjustItem</code>.
     * Adjust Item
     * @alias module:model/AdjustItem
     */
    constructor() { 
        
        AdjustItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AdjustItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AdjustItem} obj Optional instance to populate.
     * @return {module:model/AdjustItem} The populated <code>AdjustItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AdjustItem();

            if (data.hasOwnProperty('partNumber')) {
                obj['partNumber'] = ApiClient.convertToType(data['partNumber'], 'String');
            }
            if (data.hasOwnProperty('upc')) {
                obj['upc'] = ApiClient.convertToType(data['upc'], 'String');
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
            if (data.hasOwnProperty('binID')) {
                obj['binID'] = ApiClient.convertToType(data['binID'], 'Number');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Part/Product Number
 * @member {String} partNumber
 */
AdjustItem.prototype['partNumber'] = undefined;

/**
 * Universal Product Code
 * @member {String} upc
 */
AdjustItem.prototype['upc'] = undefined;

/**
 * Stock Keeping Unit
 * @member {String} sku
 */
AdjustItem.prototype['sku'] = undefined;

/**
 * Bin Location Identifier
 * @member {Number} binID
 */
AdjustItem.prototype['binID'] = undefined;

/**
 * Current Quantity of Item
 * @member {Number} quantity
 */
AdjustItem.prototype['quantity'] = undefined;






export default AdjustItem;

