/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Audit1 from './Audit1';
import AuditItem from './AuditItem';
import BaseResponse from './BaseResponse';

/**
 * The Audit model module.
 * @module model/Audit
 * @version 5.0
 */
class Audit {
    /**
     * Constructs a new <code>Audit</code>.
     * @alias module:model/Audit
     * @implements module:model/BaseResponse
     * @implements module:model/Audit1
     */
    constructor() { 
        BaseResponse.initialize(this);Audit1.initialize(this);
        Audit.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Audit</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Audit} obj Optional instance to populate.
     * @return {module:model/Audit} The populated <code>Audit</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Audit();
            BaseResponse.constructFromObject(data, obj);
            Audit1.constructFromObject(data, obj);

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('messages')) {
                obj['messages'] = ApiClient.convertToType(data['messages'], ['String']);
            }
            if (data.hasOwnProperty('numResults')) {
                obj['numResults'] = ApiClient.convertToType(data['numResults'], 'Number');
            }
            if (data.hasOwnProperty('auditID')) {
                obj['auditID'] = ApiClient.convertToType(data['auditID'], 'Number');
            }
            if (data.hasOwnProperty('userID')) {
                obj['userID'] = ApiClient.convertToType(data['userID'], 'Number');
            }
            if (data.hasOwnProperty('locationCode')) {
                obj['locationCode'] = ApiClient.convertToType(data['locationCode'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('dateRequested')) {
                obj['dateRequested'] = ApiClient.convertToType(data['dateRequested'], 'String');
            }
            if (data.hasOwnProperty('dateStarted')) {
                obj['dateStarted'] = ApiClient.convertToType(data['dateStarted'], 'String');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [AuditItem]);
            }
        }
        return obj;
    }


}

/**
 * Flag for success
 * @member {Boolean} success
 */
Audit.prototype['success'] = undefined;

/**
 * List of messages
 * @member {Array.<String>} messages
 */
Audit.prototype['messages'] = undefined;

/**
 * Number of results
 * @member {Number} numResults
 */
Audit.prototype['numResults'] = undefined;

/**
 * Audit identifier
 * @member {Number} auditID
 */
Audit.prototype['auditID'] = undefined;

/**
 * User identifier
 * @member {Number} userID
 */
Audit.prototype['userID'] = undefined;

/**
 * Location code
 * @member {String} locationCode
 */
Audit.prototype['locationCode'] = undefined;

/**
 * Audit status
 * @member {String} status
 */
Audit.prototype['status'] = undefined;

/**
 * Date the audit was requested
 * @member {String} dateRequested
 */
Audit.prototype['dateRequested'] = undefined;

/**
 * Date the audit was started
 * @member {String} dateStarted
 */
Audit.prototype['dateStarted'] = undefined;

/**
 * List of Audit Items
 * @member {Array.<module:model/AuditItem>} items
 */
Audit.prototype['items'] = undefined;


// Implement BaseResponse interface:
/**
 * Flag for success
 * @member {Boolean} success
 */
BaseResponse.prototype['success'] = undefined;
/**
 * List of messages
 * @member {Array.<String>} messages
 */
BaseResponse.prototype['messages'] = undefined;
/**
 * Number of results
 * @member {Number} numResults
 */
BaseResponse.prototype['numResults'] = undefined;
// Implement Audit1 interface:
/**
 * Audit identifier
 * @member {Number} auditID
 */
Audit1.prototype['auditID'] = undefined;
/**
 * User identifier
 * @member {Number} userID
 */
Audit1.prototype['userID'] = undefined;
/**
 * Location code
 * @member {String} locationCode
 */
Audit1.prototype['locationCode'] = undefined;
/**
 * Audit status
 * @member {String} status
 */
Audit1.prototype['status'] = undefined;
/**
 * Date the audit was requested
 * @member {String} dateRequested
 */
Audit1.prototype['dateRequested'] = undefined;
/**
 * Date the audit was started
 * @member {String} dateStarted
 */
Audit1.prototype['dateStarted'] = undefined;
/**
 * List of Audit Items
 * @member {Array.<module:model/AuditItem>} items
 */
Audit1.prototype['items'] = undefined;




export default Audit;

