/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DateRange from './DateRange';
import ProductMatch from './ProductMatch';

/**
 * The AuditSearchRequest model module.
 * @module model/AuditSearchRequest
 * @version 5.0
 */
class AuditSearchRequest {
    /**
     * Constructs a new <code>AuditSearchRequest</code>.
     * Request for searching audits
     * @alias module:model/AuditSearchRequest
     */
    constructor() { 
        
        AuditSearchRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuditSearchRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuditSearchRequest} obj Optional instance to populate.
     * @return {module:model/AuditSearchRequest} The populated <code>AuditSearchRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuditSearchRequest();

            if (data.hasOwnProperty('auditID')) {
                obj['auditID'] = ApiClient.convertToType(data['auditID'], 'Number');
            }
            if (data.hasOwnProperty('binName')) {
                obj['binName'] = ApiClient.convertToType(data['binName'], 'String');
            }
            if (data.hasOwnProperty('auditStatus')) {
                obj['auditStatus'] = ApiClient.convertToType(data['auditStatus'], 'String');
            }
            if (data.hasOwnProperty('dateRange')) {
                obj['dateRange'] = DateRange.constructFromObject(data['dateRange']);
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], [ProductMatch]);
            }
        }
        return obj;
    }


}

/**
 * Audit identifier
 * @member {Number} auditID
 */
AuditSearchRequest.prototype['auditID'] = undefined;

/**
 * Name of the bin
 * @member {String} binName
 */
AuditSearchRequest.prototype['binName'] = undefined;

/**
 * Audit Status
 * @member {String} auditStatus
 */
AuditSearchRequest.prototype['auditStatus'] = undefined;

/**
 * @member {module:model/DateRange} dateRange
 */
AuditSearchRequest.prototype['dateRange'] = undefined;

/**
 * List of matching products
 * @member {Array.<module:model/ProductMatch>} products
 */
AuditSearchRequest.prototype['products'] = undefined;






export default AuditSearchRequest;

