/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Audit from './Audit';

/**
 * The AuditSearchResponse model module.
 * @module model/AuditSearchResponse
 * @version 5.0
 */
class AuditSearchResponse {
    /**
     * Constructs a new <code>AuditSearchResponse</code>.
     * Audit Search Response
     * @alias module:model/AuditSearchResponse
     */
    constructor() { 
        
        AuditSearchResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuditSearchResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuditSearchResponse} obj Optional instance to populate.
     * @return {module:model/AuditSearchResponse} The populated <code>AuditSearchResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuditSearchResponse();

            if (data.hasOwnProperty('audits')) {
                obj['audits'] = ApiClient.convertToType(data['audits'], [Audit]);
            }
        }
        return obj;
    }


}

/**
 * List of found audits
 * @member {Array.<module:model/Audit>} audits
 */
AuditSearchResponse.prototype['audits'] = undefined;






export default AuditSearchResponse;

