/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuditItemQuantity from './AuditItemQuantity';

/**
 * The AuditItem model module.
 * @module model/AuditItem
 * @version 5.0
 */
class AuditItem {
    /**
     * Constructs a new <code>AuditItem</code>.
     * Audit Item
     * @alias module:model/AuditItem
     */
    constructor() { 
        
        AuditItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuditItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuditItem} obj Optional instance to populate.
     * @return {module:model/AuditItem} The populated <code>AuditItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuditItem();

            if (data.hasOwnProperty('auditItemID')) {
                obj['auditItemID'] = ApiClient.convertToType(data['auditItemID'], 'Number');
            }
            if (data.hasOwnProperty('binName')) {
                obj['binName'] = ApiClient.convertToType(data['binName'], 'String');
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = AuditItemQuantity.constructFromObject(data['product']);
            }
        }
        return obj;
    }


}

/**
 * Audit Item identifier
 * @member {Number} auditItemID
 */
AuditItem.prototype['auditItemID'] = undefined;

/**
 * Bin Name
 * @member {String} binName
 */
AuditItem.prototype['binName'] = undefined;

/**
 * @member {module:model/AuditItemQuantity} product
 */
AuditItem.prototype['product'] = undefined;






export default AuditItem;

