/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BaseResponse model module.
 * @module model/BaseResponse
 * @version 5.0
 */
class BaseResponse {
    /**
     * Constructs a new <code>BaseResponse</code>.
     * Base Response Model
     * @alias module:model/BaseResponse
     */
    constructor() { 
        
        BaseResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BaseResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BaseResponse} obj Optional instance to populate.
     * @return {module:model/BaseResponse} The populated <code>BaseResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BaseResponse();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('messages')) {
                obj['messages'] = ApiClient.convertToType(data['messages'], ['String']);
            }
            if (data.hasOwnProperty('numResults')) {
                obj['numResults'] = ApiClient.convertToType(data['numResults'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Flag for success
 * @member {Boolean} success
 */
BaseResponse.prototype['success'] = undefined;

/**
 * List of messages
 * @member {Array.<String>} messages
 */
BaseResponse.prototype['messages'] = undefined;

/**
 * Number of results
 * @member {Number} numResults
 */
BaseResponse.prototype['numResults'] = undefined;






export default BaseResponse;

