/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BaseResponse from './BaseResponse';
import BinInventoryResponse from './BinInventoryResponse';

/**
 * The Bin model module.
 * @module model/Bin
 * @version 5.0
 */
class Bin {
    /**
     * Constructs a new <code>Bin</code>.
     * @alias module:model/Bin
     * @implements module:model/BaseResponse
     * @implements module:model/BinInventoryResponse
     */
    constructor() { 
        BaseResponse.initialize(this);BinInventoryResponse.initialize(this);
        Bin.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Bin</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Bin} obj Optional instance to populate.
     * @return {module:model/Bin} The populated <code>Bin</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Bin();
            BaseResponse.constructFromObject(data, obj);
            BinInventoryResponse.constructFromObject(data, obj);

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('messages')) {
                obj['messages'] = ApiClient.convertToType(data['messages'], ['String']);
            }
            if (data.hasOwnProperty('numResults')) {
                obj['numResults'] = ApiClient.convertToType(data['numResults'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('binID')) {
                obj['binID'] = ApiClient.convertToType(data['binID'], 'Number');
            }
            if (data.hasOwnProperty('locationCode')) {
                obj['locationCode'] = ApiClient.convertToType(data['locationCode'], 'String');
            }
            if (data.hasOwnProperty('binTypeID')) {
                obj['binTypeID'] = ApiClient.convertToType(data['binTypeID'], 'Number');
            }
            if (data.hasOwnProperty('binStatusID')) {
                obj['binStatusID'] = ApiClient.convertToType(data['binStatusID'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Flag for success
 * @member {Boolean} success
 */
Bin.prototype['success'] = undefined;

/**
 * List of messages
 * @member {Array.<String>} messages
 */
Bin.prototype['messages'] = undefined;

/**
 * Number of results
 * @member {Number} numResults
 */
Bin.prototype['numResults'] = undefined;

/**
 * Bin Name
 * @member {String} name
 */
Bin.prototype['name'] = undefined;

/**
 * Bin ID
 * @member {Number} binID
 */
Bin.prototype['binID'] = undefined;

/**
 * Location Code
 * @member {String} locationCode
 */
Bin.prototype['locationCode'] = undefined;

/**
 * Bin Type ID
 * @member {Number} binTypeID
 */
Bin.prototype['binTypeID'] = undefined;

/**
 * Bin Status ID
 * @member {Number} binStatusID
 */
Bin.prototype['binStatusID'] = undefined;


// Implement BaseResponse interface:
/**
 * Flag for success
 * @member {Boolean} success
 */
BaseResponse.prototype['success'] = undefined;
/**
 * List of messages
 * @member {Array.<String>} messages
 */
BaseResponse.prototype['messages'] = undefined;
/**
 * Number of results
 * @member {Number} numResults
 */
BaseResponse.prototype['numResults'] = undefined;
// Implement BinInventoryResponse interface:
/**
 * Bin Name
 * @member {String} name
 */
BinInventoryResponse.prototype['name'] = undefined;
/**
 * Bin ID
 * @member {Number} binID
 */
BinInventoryResponse.prototype['binID'] = undefined;
/**
 * Location Code
 * @member {String} locationCode
 */
BinInventoryResponse.prototype['locationCode'] = undefined;
/**
 * Bin Type ID
 * @member {Number} binTypeID
 */
BinInventoryResponse.prototype['binTypeID'] = undefined;
/**
 * Bin Status ID
 * @member {Number} binStatusID
 */
BinInventoryResponse.prototype['binStatusID'] = undefined;




export default Bin;

