/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BinModel model module.
 * @module model/BinModel
 * @version 5.0
 */
class BinModel {
    /**
     * Constructs a new <code>BinModel</code>.
     * Bin Model
     * @alias module:model/BinModel
     */
    constructor() { 
        
        BinModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BinModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BinModel} obj Optional instance to populate.
     * @return {module:model/BinModel} The populated <code>BinModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BinModel();

            if (data.hasOwnProperty('binID')) {
                obj['binID'] = ApiClient.convertToType(data['binID'], 'Number');
            }
            if (data.hasOwnProperty('locationID')) {
                obj['locationID'] = ApiClient.convertToType(data['locationID'], 'Number');
            }
            if (data.hasOwnProperty('binTypeID')) {
                obj['binTypeID'] = ApiClient.convertToType(data['binTypeID'], 'Number');
            }
            if (data.hasOwnProperty('binStatusID')) {
                obj['binStatusID'] = ApiClient.convertToType(data['binStatusID'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Unique Bin Identifier assigned by the system
 * @member {Number} binID
 */
BinModel.prototype['binID'] = undefined;

/**
 * Location Identifier of the owning location
 * @member {Number} locationID
 */
BinModel.prototype['locationID'] = undefined;

/**
 * New Bin's Type ID
 * @member {Number} binTypeID
 */
BinModel.prototype['binTypeID'] = undefined;

/**
 * New Bin's Status ID
 * @member {Number} binStatusID
 */
BinModel.prototype['binStatusID'] = undefined;

/**
 * Client specified static bin name
 * @member {Number} name
 */
BinModel.prototype['name'] = undefined;






export default BinModel;

