/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BinRange model module.
 * @module model/BinRange
 * @version 5.0
 */
class BinRange {
    /**
     * Constructs a new <code>BinRange</code>.
     * Range of bins
     * @alias module:model/BinRange
     */
    constructor() { 
        
        BinRange.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BinRange</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BinRange} obj Optional instance to populate.
     * @return {module:model/BinRange} The populated <code>BinRange</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BinRange();

            if (data.hasOwnProperty('startBinName')) {
                obj['startBinName'] = ApiClient.convertToType(data['startBinName'], 'String');
            }
            if (data.hasOwnProperty('endBinName')) {
                obj['endBinName'] = ApiClient.convertToType(data['endBinName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Start Bin Name
 * @member {String} startBinName
 */
BinRange.prototype['startBinName'] = undefined;

/**
 * End Bin Name
 * @member {String} endBinName
 */
BinRange.prototype['endBinName'] = undefined;






export default BinRange;

