/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BinModel from './BinModel';

/**
 * The BinResponseModel model module.
 * @module model/BinResponseModel
 * @version 5.0
 */
class BinResponseModel {
    /**
     * Constructs a new <code>BinResponseModel</code>.
     * Bin Response Object
     * @alias module:model/BinResponseModel
     */
    constructor() { 
        
        BinResponseModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BinResponseModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BinResponseModel} obj Optional instance to populate.
     * @return {module:model/BinResponseModel} The populated <code>BinResponseModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BinResponseModel();

            if (data.hasOwnProperty('bins')) {
                obj['bins'] = BinModel.constructFromObject(data['bins']);
            }
            if (data.hasOwnProperty('resultCount')) {
                obj['resultCount'] = ApiClient.convertToType(data['resultCount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/BinModel} bins
 */
BinResponseModel.prototype['bins'] = undefined;

/**
 * number of results
 * @member {Number} resultCount
 */
BinResponseModel.prototype['resultCount'] = undefined;






export default BinResponseModel;

