/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Product from './Product';

/**
 * The BinSearchRequest model module.
 * @module model/BinSearchRequest
 * @version 5.0
 */
class BinSearchRequest {
    /**
     * Constructs a new <code>BinSearchRequest</code>.
     * Request needed for searching for bins
     * @alias module:model/BinSearchRequest
     */
    constructor() { 
        
        BinSearchRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BinSearchRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BinSearchRequest} obj Optional instance to populate.
     * @return {module:model/BinSearchRequest} The populated <code>BinSearchRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BinSearchRequest();

            if (data.hasOwnProperty('binName')) {
                obj['binName'] = ApiClient.convertToType(data['binName'], 'String');
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = Product.constructFromObject(data['product']);
            }
            if (data.hasOwnProperty('sortAscending')) {
                obj['sortAscending'] = ApiClient.convertToType(data['sortAscending'], 'Boolean');
            }
            if (data.hasOwnProperty('showNegativeInventory')) {
                obj['showNegativeInventory'] = ApiClient.convertToType(data['showNegativeInventory'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Partial match of bin name
 * @member {String} binName
 */
BinSearchRequest.prototype['binName'] = undefined;

/**
 * @member {module:model/Product} product
 */
BinSearchRequest.prototype['product'] = undefined;

/**
 * Flag for sorting ascending
 * @member {Boolean} sortAscending
 */
BinSearchRequest.prototype['sortAscending'] = undefined;

/**
 * Flag for showing negative inventory
 * @member {Boolean} showNegativeInventory
 */
BinSearchRequest.prototype['showNegativeInventory'] = undefined;






export default BinSearchRequest;

