/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BinTypeModel model module.
 * @module model/BinTypeModel
 * @version 5.0
 */
class BinTypeModel {
    /**
     * Constructs a new <code>BinTypeModel</code>.
     * Type of Bin
     * @alias module:model/BinTypeModel
     */
    constructor() { 
        
        BinTypeModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BinTypeModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BinTypeModel} obj Optional instance to populate.
     * @return {module:model/BinTypeModel} The populated <code>BinTypeModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BinTypeModel();

            if (data.hasOwnProperty('binTypeID')) {
                obj['binTypeID'] = ApiClient.convertToType(data['binTypeID'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Bin Type Identifier
 * @member {Number} binTypeID
 */
BinTypeModel.prototype['binTypeID'] = undefined;

/**
 * Bin Type Description
 * @member {String} description
 */
BinTypeModel.prototype['description'] = undefined;






export default BinTypeModel;

