/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CompleteWaveResponse model module.
 * @module model/CompleteWaveResponse
 * @version 5.0
 */
class CompleteWaveResponse {
    /**
     * Constructs a new <code>CompleteWaveResponse</code>.
     * Complete Wave Response
     * @alias module:model/CompleteWaveResponse
     */
    constructor() { 
        
        CompleteWaveResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CompleteWaveResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CompleteWaveResponse} obj Optional instance to populate.
     * @return {module:model/CompleteWaveResponse} The populated <code>CompleteWaveResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CompleteWaveResponse();

            if (data.hasOwnProperty('recoveryWaveID')) {
                obj['recoveryWaveID'] = ApiClient.convertToType(data['recoveryWaveID'], 'Number');
            }
            if (data.hasOwnProperty('auditID')) {
                obj['auditID'] = ApiClient.convertToType(data['auditID'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Recovery Wave Identifier
 * @member {Number} recoveryWaveID
 */
CompleteWaveResponse.prototype['recoveryWaveID'] = undefined;

/**
 * Audit Identifier
 * @member {Number} auditID
 */
CompleteWaveResponse.prototype['auditID'] = undefined;






export default CompleteWaveResponse;

