/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExportSettings from './ExportSettings';

/**
 * The CreateExportSettingsRequest model module.
 * @module model/CreateExportSettingsRequest
 * @version 5.0
 */
class CreateExportSettingsRequest {
    /**
     * Constructs a new <code>CreateExportSettingsRequest</code>.
     * Request needed for creating Export Settings
     * @alias module:model/CreateExportSettingsRequest
     * @param exportSettings {module:model/ExportSettings} 
     */
    constructor(exportSettings) { 
        
        CreateExportSettingsRequest.initialize(this, exportSettings);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, exportSettings) { 
        obj['exportSettings'] = exportSettings;
    }

    /**
     * Constructs a <code>CreateExportSettingsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateExportSettingsRequest} obj Optional instance to populate.
     * @return {module:model/CreateExportSettingsRequest} The populated <code>CreateExportSettingsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateExportSettingsRequest();

            if (data.hasOwnProperty('exportSettings')) {
                obj['exportSettings'] = ExportSettings.constructFromObject(data['exportSettings']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/ExportSettings} exportSettings
 */
CreateExportSettingsRequest.prototype['exportSettings'] = undefined;






export default CreateExportSettingsRequest;

