/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BinRange from './BinRange';
import DateRange from './DateRange';

/**
 * The CreateWaveRequest model module.
 * @module model/CreateWaveRequest
 * @version 5.0
 */
class CreateWaveRequest {
    /**
     * Constructs a new <code>CreateWaveRequest</code>.
     * Create Wave Request
     * @alias module:model/CreateWaveRequest
     */
    constructor() { 
        
        CreateWaveRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateWaveRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateWaveRequest} obj Optional instance to populate.
     * @return {module:model/CreateWaveRequest} The populated <code>CreateWaveRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateWaveRequest();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('maxOrders')) {
                obj['maxOrders'] = ApiClient.convertToType(data['maxOrders'], 'Number');
            }
            if (data.hasOwnProperty('includeZeroInventory')) {
                obj['includeZeroInventory'] = ApiClient.convertToType(data['includeZeroInventory'], 'Boolean');
            }
            if (data.hasOwnProperty('binRanges')) {
                obj['binRanges'] = ApiClient.convertToType(data['binRanges'], [BinRange]);
            }
            if (data.hasOwnProperty('orderDateRange')) {
                obj['orderDateRange'] = DateRange.constructFromObject(data['orderDateRange']);
            }
            if (data.hasOwnProperty('products')) {
                obj['products'] = ApiClient.convertToType(data['products'], 'String');
            }
            if (data.hasOwnProperty('shippingOptions')) {
                obj['shippingOptions'] = ApiClient.convertToType(data['shippingOptions'], 'String');
            }
            if (data.hasOwnProperty('customOrderItemData')) {
                obj['customOrderItemData'] = ApiClient.convertToType(data['customOrderItemData'], [['String']]);
            }
        }
        return obj;
    }


}

/**
 * Type of wave
 * @member {module:model/CreateWaveRequest.TypeEnum} type
 */
CreateWaveRequest.prototype['type'] = undefined;

/**
 * Maximum number of orders
 * @member {Number} maxOrders
 */
CreateWaveRequest.prototype['maxOrders'] = undefined;

/**
 * Flag for including zero inventory items
 * @member {Boolean} includeZeroInventory
 */
CreateWaveRequest.prototype['includeZeroInventory'] = undefined;

/**
 * List of Bin Ranges
 * @member {Array.<module:model/BinRange>} binRanges
 */
CreateWaveRequest.prototype['binRanges'] = undefined;

/**
 * @member {module:model/DateRange} orderDateRange
 */
CreateWaveRequest.prototype['orderDateRange'] = undefined;

/**
 * Part/Product Number
 * @member {String} products
 */
CreateWaveRequest.prototype['products'] = undefined;

/**
 * Shipping Options
 * @member {module:model/CreateWaveRequest.ShippingOptionsEnum} shippingOptions
 */
CreateWaveRequest.prototype['shippingOptions'] = undefined;

/**
 * Custom order item data
 * @member {Array.<Array.<String>>} customOrderItemData
 */
CreateWaveRequest.prototype['customOrderItemData'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CreateWaveRequest['TypeEnum'] = {

    /**
     * value: "NORMAL"
     * @const
     */
    "NORMAL": "NORMAL",

    /**
     * value: "SPECIAL"
     * @const
     */
    "SPECIAL": "SPECIAL",

    /**
     * value: "SINGLE"
     * @const
     */
    "SINGLE": "SINGLE",

    /**
     * value: "MULTIPLE"
     * @const
     */
    "MULTIPLE": "MULTIPLE"
};


/**
 * Allowed values for the <code>shippingOptions</code> property.
 * @enum {String}
 * @readonly
 */
CreateWaveRequest['ShippingOptionsEnum'] = {

    /**
     * value: "STANDARD_ONLY"
     * @const
     */
    "STANDARD_ONLY": "STANDARD_ONLY",

    /**
     * value: "EXPRESS_ONLY"
     * @const
     */
    "EXPRESS_ONLY": "EXPRESS_ONLY",

    /**
     * value: "ALL"
     * @const
     */
    "ALL": "ALL"
};



export default CreateWaveRequest;

