/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExportSettingsS3 from './ExportSettingsS3';

/**
 * The CreateExportSettingsS3Request model module.
 * @module model/CreateExportSettingsS3Request
 * @version 5.0
 */
class CreateExportSettingsS3Request {
    /**
     * Constructs a new <code>CreateExportSettingsS3Request</code>.
     * Request needed for creating Export Settings S3
     * @alias module:model/CreateExportSettingsS3Request
     * @param exportSettingsName {String} Export Settings Name to associate the ftp settings with
     * @param exportSettingsS3 {module:model/ExportSettingsS3} 
     */
    constructor(exportSettingsName, exportSettingsS3) { 
        
        CreateExportSettingsS3Request.initialize(this, exportSettingsName, exportSettingsS3);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, exportSettingsName, exportSettingsS3) { 
        obj['exportSettingsName'] = exportSettingsName;
        obj['exportSettingsS3'] = exportSettingsS3;
    }

    /**
     * Constructs a <code>CreateExportSettingsS3Request</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateExportSettingsS3Request} obj Optional instance to populate.
     * @return {module:model/CreateExportSettingsS3Request} The populated <code>CreateExportSettingsS3Request</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateExportSettingsS3Request();

            if (data.hasOwnProperty('exportSettingsName')) {
                obj['exportSettingsName'] = ApiClient.convertToType(data['exportSettingsName'], 'String');
            }
            if (data.hasOwnProperty('exportSettingsS3')) {
                obj['exportSettingsS3'] = ExportSettingsS3.constructFromObject(data['exportSettingsS3']);
            }
        }
        return obj;
    }


}

/**
 * Export Settings Name to associate the ftp settings with
 * @member {String} exportSettingsName
 */
CreateExportSettingsS3Request.prototype['exportSettingsName'] = undefined;

/**
 * @member {module:model/ExportSettingsS3} exportSettingsS3
 */
CreateExportSettingsS3Request.prototype['exportSettingsS3'] = undefined;






export default CreateExportSettingsS3Request;

