/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MDeleteItem from './MDeleteItem';

/**
 * The DeleteItemResponse model module.
 * @module model/DeleteItemResponse
 * @version 5.0
 */
class DeleteItemResponse {
    /**
     * Constructs a new <code>DeleteItemResponse</code>.
     * Delete Item Response
     * @alias module:model/DeleteItemResponse
     */
    constructor() { 
        
        DeleteItemResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeleteItemResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteItemResponse} obj Optional instance to populate.
     * @return {module:model/DeleteItemResponse} The populated <code>DeleteItemResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteItemResponse();

            if (data.hasOwnProperty('dryRun')) {
                obj['dryRun'] = ApiClient.convertToType(data['dryRun'], 'Boolean');
            }
            if (data.hasOwnProperty('itemsDeleted')) {
                obj['itemsDeleted'] = ApiClient.convertToType(data['itemsDeleted'], [MDeleteItem]);
            }
            if (data.hasOwnProperty('totalAuditsDeleted')) {
                obj['totalAuditsDeleted'] = ApiClient.convertToType(data['totalAuditsDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('totalInventoryEntriesDeleted')) {
                obj['totalInventoryEntriesDeleted'] = ApiClient.convertToType(data['totalInventoryEntriesDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('totalLocationsAffected')) {
                obj['totalLocationsAffected'] = ApiClient.convertToType(data['totalLocationsAffected'], 'Boolean');
            }
            if (data.hasOwnProperty('totalPickWavesDeleted')) {
                obj['totalPickWavesDeleted'] = ApiClient.convertToType(data['totalPickWavesDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('totalProductsDeleted')) {
                obj['totalProductsDeleted'] = ApiClient.convertToType(data['totalProductsDeleted'], 'Boolean');
            }
            if (data.hasOwnProperty('jobIDs')) {
                obj['jobIDs'] = ApiClient.convertToType(data['jobIDs'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Flag used to differentiate between a test and a non-test run.
 * @member {Boolean} dryRun
 */
DeleteItemResponse.prototype['dryRun'] = undefined;

/**
 * Items deleted due to the request
 * @member {Array.<module:model/MDeleteItem>} itemsDeleted
 */
DeleteItemResponse.prototype['itemsDeleted'] = undefined;

/**
 * Flag used to differentiate between a test and a non-test run.
 * @member {Boolean} totalAuditsDeleted
 */
DeleteItemResponse.prototype['totalAuditsDeleted'] = undefined;

/**
 * Flag used to differentiate between a test and a non-test run.
 * @member {Boolean} totalInventoryEntriesDeleted
 */
DeleteItemResponse.prototype['totalInventoryEntriesDeleted'] = undefined;

/**
 * Flag used to differentiate between a test and a non-test run.
 * @member {Boolean} totalLocationsAffected
 */
DeleteItemResponse.prototype['totalLocationsAffected'] = undefined;

/**
 * Flag used to differentiate between a test and a non-test run.
 * @member {Boolean} totalPickWavesDeleted
 */
DeleteItemResponse.prototype['totalPickWavesDeleted'] = undefined;

/**
 * Flag used to differentiate between a test and a non-test run.
 * @member {Boolean} totalProductsDeleted
 */
DeleteItemResponse.prototype['totalProductsDeleted'] = undefined;

/**
 * Flag used to differentiate between a test and a non-test run.
 * @member {Boolean} jobIDs
 */
DeleteItemResponse.prototype['jobIDs'] = undefined;






export default DeleteItemResponse;

