/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteItemRequest model module.
 * @module model/DeleteItemRequest
 * @version 5.0
 */
class DeleteItemRequest {
    /**
     * Constructs a new <code>DeleteItemRequest</code>.
     * Request needed for deleting inventory
     * @alias module:model/DeleteItemRequest
     */
    constructor() { 
        
        DeleteItemRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeleteItemRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteItemRequest} obj Optional instance to populate.
     * @return {module:model/DeleteItemRequest} The populated <code>DeleteItemRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteItemRequest();

            if (data.hasOwnProperty('dryRun')) {
                obj['dryRun'] = ApiClient.convertToType(data['dryRun'], 'Boolean');
            }
            if (data.hasOwnProperty('explicit')) {
                obj['explicit'] = ApiClient.convertToType(data['explicit'], 'Boolean');
            }
            if (data.hasOwnProperty('locationCodes')) {
                obj['locationCodes'] = ApiClient.convertToType(data['locationCodes'], ['String']);
            }
            if (data.hasOwnProperty('partNumber')) {
                obj['partNumber'] = ApiClient.convertToType(data['partNumber'], 'String');
            }
            if (data.hasOwnProperty('upc')) {
                obj['upc'] = ApiClient.convertToType(data['upc'], 'String');
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Flag used to differentiate between a test and a non-test run.
 * @member {Boolean} dryRun
 */
DeleteItemRequest.prototype['dryRun'] = undefined;

/**
 * Flag used to request explicit inventory, location, pick wave, and audit information for each request item.
 * @member {Boolean} explicit
 */
DeleteItemRequest.prototype['explicit'] = undefined;

/**
 * An array of locationCodes to be considered for item-deletion purposes. Optional.     All locationCodes associated with the requesting tenant will be considered if no locationCodes are provided.
 * @member {Array.<String>} locationCodes
 */
DeleteItemRequest.prototype['locationCodes'] = undefined;

/**
 * The part number of the item to be deleted. Supports basic regex operators: .*+?^$[]
 * @member {String} partNumber
 */
DeleteItemRequest.prototype['partNumber'] = undefined;

/**
 * The upc of the item to be deleted. Supports basic regex operators: .*+?^$[]
 * @member {String} upc
 */
DeleteItemRequest.prototype['upc'] = undefined;

/**
 * The sku of the item to be deleted. Supports basic regex operators: .*+?^$[]
 * @member {String} sku
 */
DeleteItemRequest.prototype['sku'] = undefined;






export default DeleteItemRequest;

