/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetBinsRequest model module.
 * @module model/GetBinsRequest
 * @version 5.0
 */
class GetBinsRequest {
    /**
     * Constructs a new <code>GetBinsRequest</code>.
     * Request needed for getting a list of bins
     * @alias module:model/GetBinsRequest
     */
    constructor() { 
        
        GetBinsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetBinsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetBinsRequest} obj Optional instance to populate.
     * @return {module:model/GetBinsRequest} The populated <code>GetBinsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetBinsRequest();

            if (data.hasOwnProperty('searchTerm')) {
                obj['searchTerm'] = ApiClient.convertToType(data['searchTerm'], 'String');
            }
        }
        return obj;
    }


}

/**
 * term to search for
 * @member {String} searchTerm
 */
GetBinsRequest.prototype['searchTerm'] = undefined;






export default GetBinsRequest;

