/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PendingItem from './PendingItem';

/**
 * The GetPendingItemsResponse model module.
 * @module model/GetPendingItemsResponse
 * @version 5.0
 */
class GetPendingItemsResponse {
    /**
     * Constructs a new <code>GetPendingItemsResponse</code>.
     * Get Pending Items Response
     * @alias module:model/GetPendingItemsResponse
     */
    constructor() { 
        
        GetPendingItemsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetPendingItemsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetPendingItemsResponse} obj Optional instance to populate.
     * @return {module:model/GetPendingItemsResponse} The populated <code>GetPendingItemsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetPendingItemsResponse();

            if (data.hasOwnProperty('totalCount')) {
                obj['totalCount'] = ApiClient.convertToType(data['totalCount'], 'Number');
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
            if (data.hasOwnProperty('perPage')) {
                obj['perPage'] = ApiClient.convertToType(data['perPage'], 'Number');
            }
            if (data.hasOwnProperty('prevPage')) {
                obj['prevPage'] = ApiClient.convertToType(data['prevPage'], 'Number');
            }
            if (data.hasOwnProperty('sortBy')) {
                obj['sortBy'] = ApiClient.convertToType(data['sortBy'], 'String');
            }
            if (data.hasOwnProperty('sortAscending')) {
                obj['sortAscending'] = ApiClient.convertToType(data['sortAscending'], 'Boolean');
            }
            if (data.hasOwnProperty('pendingItems')) {
                obj['pendingItems'] = ApiClient.convertToType(data['pendingItems'], [PendingItem]);
            }
        }
        return obj;
    }


}

/**
 * Total Count of pending items
 * @member {Number} totalCount
 */
GetPendingItemsResponse.prototype['totalCount'] = undefined;

/**
 * Page number
 * @member {Number} page
 */
GetPendingItemsResponse.prototype['page'] = undefined;

/**
 * Number per page
 * @member {Number} perPage
 */
GetPendingItemsResponse.prototype['perPage'] = undefined;

/**
 * Previous page
 * @member {Number} prevPage
 */
GetPendingItemsResponse.prototype['prevPage'] = undefined;

/**
 * Field to sort by
 * @member {module:model/GetPendingItemsResponse.SortByEnum} sortBy
 */
GetPendingItemsResponse.prototype['sortBy'] = undefined;

/**
 * Flag to sort by ascending
 * @member {Boolean} sortAscending
 */
GetPendingItemsResponse.prototype['sortAscending'] = undefined;

/**
 * List of pending items
 * @member {Array.<module:model/PendingItem>} pendingItems
 */
GetPendingItemsResponse.prototype['pendingItems'] = undefined;





/**
 * Allowed values for the <code>sortBy</code> property.
 * @enum {String}
 * @readonly
 */
GetPendingItemsResponse['SortByEnum'] = {

    /**
     * value: "QUANTITY"
     * @const
     */
    "QUANTITY": "QUANTITY",

    /**
     * value: "FROM"
     * @const
     */
    "FROM": "FROM",

    /**
     * value: "TO"
     * @const
     */
    "TO": "TO",

    /**
     * value: "TYPE"
     * @const
     */
    "TYPE": "TYPE",

    /**
     * value: "ORDER_ID"
     * @const
     */
    "ORDER_ID": "ORDER_ID",

    /**
     * value: "WEIGHT"
     * @const
     */
    "WEIGHT": "WEIGHT"
};



export default GetPendingItemsResponse;

