/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JobIDResponse model module.
 * @module model/JobIDResponse
 * @version 5.0
 */
class JobIDResponse {
    /**
     * Constructs a new <code>JobIDResponse</code>.
     * Job ID Response
     * @alias module:model/JobIDResponse
     */
    constructor() { 
        
        JobIDResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JobIDResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobIDResponse} obj Optional instance to populate.
     * @return {module:model/JobIDResponse} The populated <code>JobIDResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobIDResponse();

            if (data.hasOwnProperty('jobID')) {
                obj['jobID'] = ApiClient.convertToType(data['jobID'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Job ID
 * @member {Number} jobID
 */
JobIDResponse.prototype['jobID'] = undefined;






export default JobIDResponse;

