/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MItemIdentifier from './MItemIdentifier';

/**
 * The MDeleteItem model module.
 * @module model/MDeleteItem
 * @version 5.0
 */
class MDeleteItem {
    /**
     * Constructs a new <code>MDeleteItem</code>.
     * Delete Item Model
     * @alias module:model/MDeleteItem
     */
    constructor() { 
        
        MDeleteItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MDeleteItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MDeleteItem} obj Optional instance to populate.
     * @return {module:model/MDeleteItem} The populated <code>MDeleteItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MDeleteItem();

            if (data.hasOwnProperty('productID')) {
                obj['productID'] = ApiClient.convertToType(data['productID'], 'Number');
            }
            if (data.hasOwnProperty('inventoryIDs')) {
                obj['inventoryIDs'] = ApiClient.convertToType(data['inventoryIDs'], ['Number']);
            }
            if (data.hasOwnProperty('locationIDs')) {
                obj['locationIDs'] = ApiClient.convertToType(data['locationIDs'], ['Number']);
            }
            if (data.hasOwnProperty('auditIDs')) {
                obj['auditIDs'] = ApiClient.convertToType(data['auditIDs'], ['Number']);
            }
            if (data.hasOwnProperty('pickWaveIDs')) {
                obj['pickWaveIDs'] = ApiClient.convertToType(data['pickWaveIDs'], ['Number']);
            }
            if (data.hasOwnProperty('itemIdentifier')) {
                obj['itemIdentifier'] = MItemIdentifier.constructFromObject(data['itemIdentifier']);
            }
        }
        return obj;
    }


}

/**
 * Product Identifier
 * @member {Number} productID
 */
MDeleteItem.prototype['productID'] = undefined;

/**
 * List of inventory identifiers associated with the deleted item
 * @member {Array.<Number>} inventoryIDs
 */
MDeleteItem.prototype['inventoryIDs'] = undefined;

/**
 * List of location identifiers associated with the deleted item
 * @member {Array.<Number>} locationIDs
 */
MDeleteItem.prototype['locationIDs'] = undefined;

/**
 * List of audit identifiers associated with the deleted item
 * @member {Array.<Number>} auditIDs
 */
MDeleteItem.prototype['auditIDs'] = undefined;

/**
 * List of pick wave identifiers associated with the deleted item
 * @member {Array.<Number>} pickWaveIDs
 */
MDeleteItem.prototype['pickWaveIDs'] = undefined;

/**
 * @member {module:model/MItemIdentifier} itemIdentifier
 */
MDeleteItem.prototype['itemIdentifier'] = undefined;






export default MDeleteItem;

