/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MFetchFileConfig model module.
 * @module model/MFetchFileConfig
 * @version 5.0
 */
class MFetchFileConfig {
    /**
     * Constructs a new <code>MFetchFileConfig</code>.
     * Fetch File Config Model
     * @alias module:model/MFetchFileConfig
     */
    constructor() { 
        
        MFetchFileConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MFetchFileConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MFetchFileConfig} obj Optional instance to populate.
     * @return {module:model/MFetchFileConfig} The populated <code>MFetchFileConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MFetchFileConfig();

            if (data.hasOwnProperty('fetchFileConfigID')) {
                obj['fetchFileConfigID'] = ApiClient.convertToType(data['fetchFileConfigID'], 'Number');
            }
            if (data.hasOwnProperty('tenantID')) {
                obj['tenantID'] = ApiClient.convertToType(data['tenantID'], 'Number');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('lastModified')) {
                obj['lastModified'] = ApiClient.convertToType(data['lastModified'], 'String');
            }
            if (data.hasOwnProperty('emailList')) {
                obj['emailList'] = ApiClient.convertToType(data['emailList'], 'String');
            }
            if (data.hasOwnProperty('refreshEnabled')) {
                obj['refreshEnabled'] = ApiClient.convertToType(data['refreshEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('refreshFileDescription')) {
                obj['refreshFileDescription'] = ApiClient.convertToType(data['refreshFileDescription'], 'String');
            }
            if (data.hasOwnProperty('updateEnabled')) {
                obj['updateEnabled'] = ApiClient.convertToType(data['updateEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('updateFileDescription')) {
                obj['updateFileDescription'] = ApiClient.convertToType(data['updateFileDescription'], 'String');
            }
            if (data.hasOwnProperty('ftpServer')) {
                obj['ftpServer'] = ApiClient.convertToType(data['ftpServer'], 'String');
            }
            if (data.hasOwnProperty('ftpUsername')) {
                obj['ftpUsername'] = ApiClient.convertToType(data['ftpUsername'], 'String');
            }
            if (data.hasOwnProperty('ftpPassword')) {
                obj['ftpPassword'] = ApiClient.convertToType(data['ftpPassword'], 'String');
            }
            if (data.hasOwnProperty('ftpPort')) {
                obj['ftpPort'] = ApiClient.convertToType(data['ftpPort'], 'Number');
            }
            if (data.hasOwnProperty('ftpRemotePath')) {
                obj['ftpRemotePath'] = ApiClient.convertToType(data['ftpRemotePath'], 'String');
            }
            if (data.hasOwnProperty('ftpRemotePathArchive')) {
                obj['ftpRemotePathArchive'] = ApiClient.convertToType(data['ftpRemotePathArchive'], 'String');
            }
            if (data.hasOwnProperty('lockName')) {
                obj['lockName'] = ApiClient.convertToType(data['lockName'], 'String');
            }
            if (data.hasOwnProperty('postProcessAction')) {
                obj['postProcessAction'] = ApiClient.convertToType(data['postProcessAction'], 'Number');
            }
            if (data.hasOwnProperty('useControlFile')) {
                obj['useControlFile'] = ApiClient.convertToType(data['useControlFile'], 'Boolean');
            }
            if (data.hasOwnProperty('multipleFiles')) {
                obj['multipleFiles'] = ApiClient.convertToType(data['multipleFiles'], 'Boolean');
            }
            if (data.hasOwnProperty('zeroOutNegatives')) {
                obj['zeroOutNegatives'] = ApiClient.convertToType(data['zeroOutNegatives'], 'Boolean');
            }
            if (data.hasOwnProperty('fieldNameMap')) {
                obj['fieldNameMap'] = ApiClient.convertToType(data['fieldNameMap'], ['String']);
            }
            if (data.hasOwnProperty('ignoreExtraFields')) {
                obj['ignoreExtraFields'] = ApiClient.convertToType(data['ignoreExtraFields'], 'Boolean');
            }
            if (data.hasOwnProperty('blankQuantityIsZero')) {
                obj['blankQuantityIsZero'] = ApiClient.convertToType(data['blankQuantityIsZero'], 'Boolean');
            }
            if (data.hasOwnProperty('csvDelimiter')) {
                obj['csvDelimiter'] = ApiClient.convertToType(data['csvDelimiter'], 'String');
            }
            if (data.hasOwnProperty('exportAfterRefresh')) {
                obj['exportAfterRefresh'] = ApiClient.convertToType(data['exportAfterRefresh'], 'Boolean');
            }
            if (data.hasOwnProperty('postImportExportId')) {
                obj['postImportExportId'] = ApiClient.convertToType(data['postImportExportId'], 'Number');
            }
            if (data.hasOwnProperty('postImportFtpId')) {
                obj['postImportFtpId'] = ApiClient.convertToType(data['postImportFtpId'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Fetch File Config ID
 * @member {Number} fetchFileConfigID
 */
MFetchFileConfig.prototype['fetchFileConfigID'] = undefined;

/**
 * Tenant ID
 * @member {Number} tenantID
 */
MFetchFileConfig.prototype['tenantID'] = undefined;

/**
 * Active
 * @member {Boolean} active
 */
MFetchFileConfig.prototype['active'] = undefined;

/**
 * Time config was last modified
 * @member {String} lastModified
 */
MFetchFileConfig.prototype['lastModified'] = undefined;

/**
 * Email List
 * @member {String} emailList
 */
MFetchFileConfig.prototype['emailList'] = undefined;

/**
 * Flag for Refresh Enabled
 * @member {Boolean} refreshEnabled
 */
MFetchFileConfig.prototype['refreshEnabled'] = undefined;

/**
 * Description for the refresh file
 * @member {String} refreshFileDescription
 */
MFetchFileConfig.prototype['refreshFileDescription'] = undefined;

/**
 * Flag for Update Enabled
 * @member {Boolean} updateEnabled
 */
MFetchFileConfig.prototype['updateEnabled'] = undefined;

/**
 * Description for the update file
 * @member {String} updateFileDescription
 */
MFetchFileConfig.prototype['updateFileDescription'] = undefined;

/**
 * FTP server address
 * @member {String} ftpServer
 */
MFetchFileConfig.prototype['ftpServer'] = undefined;

/**
 * FTP server username
 * @member {String} ftpUsername
 */
MFetchFileConfig.prototype['ftpUsername'] = undefined;

/**
 * FTP server password
 * @member {String} ftpPassword
 */
MFetchFileConfig.prototype['ftpPassword'] = undefined;

/**
 * FTP server port
 * @member {Number} ftpPort
 */
MFetchFileConfig.prototype['ftpPort'] = undefined;

/**
 * FTP server remote path
 * @member {String} ftpRemotePath
 */
MFetchFileConfig.prototype['ftpRemotePath'] = undefined;

/**
 * FTP server remote path archive
 * @member {String} ftpRemotePathArchive
 */
MFetchFileConfig.prototype['ftpRemotePathArchive'] = undefined;

/**
 * Lock name
 * @member {String} lockName
 */
MFetchFileConfig.prototype['lockName'] = undefined;

/**
 * Enum denoting action post processing
 * @member {Number} postProcessAction
 */
MFetchFileConfig.prototype['postProcessAction'] = undefined;

/**
 * Flag for using control file
 * @member {Boolean} useControlFile
 */
MFetchFileConfig.prototype['useControlFile'] = undefined;

/**
 * Flag for using multiple files
 * @member {Boolean} multipleFiles
 */
MFetchFileConfig.prototype['multipleFiles'] = undefined;

/**
 * Flag for converting negatives to zero
 * @member {Boolean} zeroOutNegatives
 */
MFetchFileConfig.prototype['zeroOutNegatives'] = undefined;

/**
 * List of field names
 * @member {Array.<String>} fieldNameMap
 */
MFetchFileConfig.prototype['fieldNameMap'] = undefined;

/**
 * Flag for ignoring extra fields
 * @member {Boolean} ignoreExtraFields
 */
MFetchFileConfig.prototype['ignoreExtraFields'] = undefined;

/**
 * Flag to convert null quantities to zero
 * @member {Boolean} blankQuantityIsZero
 */
MFetchFileConfig.prototype['blankQuantityIsZero'] = undefined;

/**
 * CSV Delimiter
 * @member {String} csvDelimiter
 */
MFetchFileConfig.prototype['csvDelimiter'] = undefined;

/**
 * Flag for exporting after refresh
 * @member {Boolean} exportAfterRefresh
 */
MFetchFileConfig.prototype['exportAfterRefresh'] = undefined;

/**
 * Export id post import
 * @member {Number} postImportExportId
 */
MFetchFileConfig.prototype['postImportExportId'] = undefined;

/**
 * FTP id post import
 * @member {Number} postImportFtpId
 */
MFetchFileConfig.prototype['postImportFtpId'] = undefined;






export default MFetchFileConfig;

