/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Item from './Item';

/**
 * The OrderItemInformationRequest model module.
 * @module model/OrderItemInformationRequest
 * @version 5.0
 */
class OrderItemInformationRequest {
    /**
     * Constructs a new <code>OrderItemInformationRequest</code>.
     * Request for getting order item information
     * @alias module:model/OrderItemInformationRequest
     */
    constructor() { 
        
        OrderItemInformationRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderItemInformationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderItemInformationRequest} obj Optional instance to populate.
     * @return {module:model/OrderItemInformationRequest} The populated <code>OrderItemInformationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderItemInformationRequest();

            if (data.hasOwnProperty('orderID')) {
                obj['orderID'] = ApiClient.convertToType(data['orderID'], 'Number');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [Item]);
            }
        }
        return obj;
    }


}

/**
 * Order Identifier
 * @member {Number} orderID
 */
OrderItemInformationRequest.prototype['orderID'] = undefined;

/**
 * List of Items to search on
 * @member {Array.<module:model/Item>} items
 */
OrderItemInformationRequest.prototype['items'] = undefined;






export default OrderItemInformationRequest;

