/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductMapping model module.
 * @module model/ProductMapping
 * @version 5.0
 */
class ProductMapping {
    /**
     * Constructs a new <code>ProductMapping</code>.
     * Product Mapping
     * @alias module:model/ProductMapping
     */
    constructor() { 
        
        ProductMapping.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductMapping</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductMapping} obj Optional instance to populate.
     * @return {module:model/ProductMapping} The populated <code>ProductMapping</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductMapping();

            if (data.hasOwnProperty('tenantID')) {
                obj['tenantID'] = ApiClient.convertToType(data['tenantID'], 'Number');
            }
            if (data.hasOwnProperty('direction')) {
                obj['direction'] = ApiClient.convertToType(data['direction'], 'String');
            }
            if (data.hasOwnProperty('mapping')) {
                obj['mapping'] = ApiClient.convertToType(data['mapping'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Tenant Identifier
 * @member {Number} tenantID
 */
ProductMapping.prototype['tenantID'] = undefined;

/**
 * Enum for direction of the mapping
 * @member {module:model/ProductMapping.DirectionEnum} direction
 */
ProductMapping.prototype['direction'] = undefined;

/**
 * Enum for mapping rule
 * @member {module:model/ProductMapping.MappingEnum} mapping
 */
ProductMapping.prototype['mapping'] = undefined;





/**
 * Allowed values for the <code>direction</code> property.
 * @enum {String}
 * @readonly
 */
ProductMapping['DirectionEnum'] = {

    /**
     * value: "INBOUND"
     * @const
     */
    "INBOUND": "INBOUND",

    /**
     * value: "OUTBOUND"
     * @const
     */
    "OUTBOUND": "OUTBOUND",

    /**
     * value: "SKIP"
     * @const
     */
    "SKIP": "SKIP"
};


/**
 * Allowed values for the <code>mapping</code> property.
 * @enum {String}
 * @readonly
 */
ProductMapping['MappingEnum'] = {

    /**
     * value: "DEFAULT_MAPPING"
     * @const
     */
    "DEFAULT_MAPPING": "DEFAULT_MAPPING",

    /**
     * value: "CUSTOM_MAPPING_PART_TO_ALL"
     * @const
     */
    "CUSTOM_MAPPING_PART_TO_ALL": "CUSTOM_MAPPING_PART_TO_ALL",

    /**
     * value: "CUSTOM_MAPPING_PART_TO_SKU"
     * @const
     */
    "CUSTOM_MAPPING_PART_TO_SKU": "CUSTOM_MAPPING_PART_TO_SKU",

    /**
     * value: "CUSTOM_MAPPING_ONLY_UPC"
     * @const
     */
    "CUSTOM_MAPPING_ONLY_UPC": "CUSTOM_MAPPING_ONLY_UPC",

    /**
     * value: "CUSTOM_MAPPING_PART_TO_UPC_IF_EMPTY"
     * @const
     */
    "CUSTOM_MAPPING_PART_TO_UPC_IF_EMPTY": "CUSTOM_MAPPING_PART_TO_UPC_IF_EMPTY",

    /**
     * value: "CUSTOM_MAPPING_SKU_TO_PART_UPC_SKU"
     * @const
     */
    "CUSTOM_MAPPING_SKU_TO_PART_UPC_SKU": "CUSTOM_MAPPING_SKU_TO_PART_UPC_SKU",

    /**
     * value: "CUSTOM_MAPPING_SKU_TO_PART"
     * @const
     */
    "CUSTOM_MAPPING_SKU_TO_PART": "CUSTOM_MAPPING_SKU_TO_PART"
};



export default ProductMapping;

