/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RefreshItem model module.
 * @module model/RefreshItem
 * @version 5.0
 */
class RefreshItem {
    /**
     * Constructs a new <code>RefreshItem</code>.
     * Refresh Item
     * @alias module:model/RefreshItem
     */
    constructor() { 
        
        RefreshItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RefreshItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RefreshItem} obj Optional instance to populate.
     * @return {module:model/RefreshItem} The populated <code>RefreshItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RefreshItem();

            if (data.hasOwnProperty('partNumber')) {
                obj['partNumber'] = ApiClient.convertToType(data['partNumber'], 'String');
            }
            if (data.hasOwnProperty('upc')) {
                obj['upc'] = ApiClient.convertToType(data['upc'], 'String');
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
            if (data.hasOwnProperty('binID')) {
                obj['binID'] = ApiClient.convertToType(data['binID'], 'Number');
            }
            if (data.hasOwnProperty('ltd')) {
                obj['ltd'] = ApiClient.convertToType(data['ltd'], 'String');
            }
            if (data.hasOwnProperty('floor')) {
                obj['floor'] = ApiClient.convertToType(data['floor'], 'Number');
            }
            if (data.hasOwnProperty('safetyStock')) {
                obj['safetyStock'] = ApiClient.convertToType(data['safetyStock'], 'Number');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('retailPrice')) {
                obj['retailPrice'] = ApiClient.convertToType(data['retailPrice'], 'Number');
            }
            if (data.hasOwnProperty('currencyID')) {
                obj['currencyID'] = ApiClient.convertToType(data['currencyID'], 'Number');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Part/Product Number
 * @member {String} partNumber
 */
RefreshItem.prototype['partNumber'] = undefined;

/**
 * Universal Product Code
 * @member {String} upc
 */
RefreshItem.prototype['upc'] = undefined;

/**
 * Stock Keeping Unit
 * @member {String} sku
 */
RefreshItem.prototype['sku'] = undefined;

/**
 * Bin Location Identifier
 * @member {Number} binID
 */
RefreshItem.prototype['binID'] = undefined;

/**
 * Custom field used for store prioritization
 * @member {String} ltd
 */
RefreshItem.prototype['ltd'] = undefined;

/**
 * Absolute minimum quantity of this item that should be in stock at any time
 * @member {Number} floor
 */
RefreshItem.prototype['floor'] = undefined;

/**
 * Quantity of this item the location wants to keep in stock to ensure stock isn't completely depleted
 * @member {Number} safetyStock
 */
RefreshItem.prototype['safetyStock'] = undefined;

/**
 * Current Quantity of Item
 * @member {Number} quantity
 */
RefreshItem.prototype['quantity'] = undefined;

/**
 * Stock Keeping Unit
 * @member {Number} retailPrice
 */
RefreshItem.prototype['retailPrice'] = undefined;

/**
 * The price of the item
 * @member {Number} currencyID
 */
RefreshItem.prototype['currencyID'] = undefined;

/**
 * List of Item Attributes
 * @member {Array.<String>} attributes
 */
RefreshItem.prototype['attributes'] = undefined;






export default RefreshItem;

