/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExportSettingsFTP from './ExportSettingsFTP';

/**
 * The UpdateExportSettingsFTPRequest model module.
 * @module model/UpdateExportSettingsFTPRequest
 * @version 5.0
 */
class UpdateExportSettingsFTPRequest {
    /**
     * Constructs a new <code>UpdateExportSettingsFTPRequest</code>.
     * Request needed updating existing Export Settings FTP
     * @alias module:model/UpdateExportSettingsFTPRequest
     * @param exportSettingsName {String} Export Settings Name to associate the ftp settings with
     * @param exportSettingsFTP {module:model/ExportSettingsFTP} 
     */
    constructor(exportSettingsName, exportSettingsFTP) { 
        
        UpdateExportSettingsFTPRequest.initialize(this, exportSettingsName, exportSettingsFTP);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, exportSettingsName, exportSettingsFTP) { 
        obj['exportSettingsName'] = exportSettingsName;
        obj['exportSettingsFTP'] = exportSettingsFTP;
    }

    /**
     * Constructs a <code>UpdateExportSettingsFTPRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateExportSettingsFTPRequest} obj Optional instance to populate.
     * @return {module:model/UpdateExportSettingsFTPRequest} The populated <code>UpdateExportSettingsFTPRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateExportSettingsFTPRequest();

            if (data.hasOwnProperty('exportSettingsName')) {
                obj['exportSettingsName'] = ApiClient.convertToType(data['exportSettingsName'], 'String');
            }
            if (data.hasOwnProperty('exportSettingsFTP')) {
                obj['exportSettingsFTP'] = ExportSettingsFTP.constructFromObject(data['exportSettingsFTP']);
            }
        }
        return obj;
    }


}

/**
 * Export Settings Name to associate the ftp settings with
 * @member {String} exportSettingsName
 */
UpdateExportSettingsFTPRequest.prototype['exportSettingsName'] = undefined;

/**
 * @member {module:model/ExportSettingsFTP} exportSettingsFTP
 */
UpdateExportSettingsFTPRequest.prototype['exportSettingsFTP'] = undefined;






export default UpdateExportSettingsFTPRequest;

