/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateExportSettingsS3Response model module.
 * @module model/UpdateExportSettingsS3Response
 * @version 5.0
 */
class UpdateExportSettingsS3Response {
    /**
     * Constructs a new <code>UpdateExportSettingsS3Response</code>.
     * Update Export Settings S3 Response
     * @alias module:model/UpdateExportSettingsS3Response
     */
    constructor() { 
        
        UpdateExportSettingsS3Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateExportSettingsS3Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateExportSettingsS3Response} obj Optional instance to populate.
     * @return {module:model/UpdateExportSettingsS3Response} The populated <code>UpdateExportSettingsS3Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateExportSettingsS3Response();

            if (data.hasOwnProperty('tenantID')) {
                obj['tenantID'] = ApiClient.convertToType(data['tenantID'], 'Number');
            }
            if (data.hasOwnProperty('exportSettingsS3ID')) {
                obj['exportSettingsS3ID'] = ApiClient.convertToType(data['exportSettingsS3ID'], 'Number');
            }
            if (data.hasOwnProperty('exportSettingsID')) {
                obj['exportSettingsID'] = ApiClient.convertToType(data['exportSettingsID'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Tenant ID
 * @member {Number} tenantID
 */
UpdateExportSettingsS3Response.prototype['tenantID'] = undefined;

/**
 * Export Settings S3 ID
 * @member {Number} exportSettingsS3ID
 */
UpdateExportSettingsS3Response.prototype['exportSettingsS3ID'] = undefined;

/**
 * Export Settings ID to associate the s3 settings with
 * @member {Number} exportSettingsID
 */
UpdateExportSettingsS3Response.prototype['exportSettingsID'] = undefined;






export default UpdateExportSettingsS3Response;

