/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdateBinRequest from './UpdateBinRequest';

/**
 * The UpdateBinsRequest model module.
 * @module model/UpdateBinsRequest
 * @version 5.0
 */
class UpdateBinsRequest {
    /**
     * Constructs a new <code>UpdateBinsRequest</code>.
     * Request needed for updating bins
     * @alias module:model/UpdateBinsRequest
     */
    constructor() { 
        
        UpdateBinsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateBinsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateBinsRequest} obj Optional instance to populate.
     * @return {module:model/UpdateBinsRequest} The populated <code>UpdateBinsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateBinsRequest();

            if (data.hasOwnProperty('bins')) {
                obj['bins'] = ApiClient.convertToType(data['bins'], [UpdateBinRequest]);
            }
        }
        return obj;
    }


}

/**
 * List of Update Bin Requests
 * @member {Array.<module:model/UpdateBinRequest>} bins
 */
UpdateBinsRequest.prototype['bins'] = undefined;






export default UpdateBinsRequest;

