/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateBinRequest model module.
 * @module model/UpdateBinRequest
 * @version 5.0
 */
class UpdateBinRequest {
    /**
     * Constructs a new <code>UpdateBinRequest</code>.
     * Request needed for updating a bin
     * @alias module:model/UpdateBinRequest
     * @param binID {Number} Bin identifier
     */
    constructor(binID) { 
        
        UpdateBinRequest.initialize(this, binID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, binID) { 
        obj['binID'] = binID;
    }

    /**
     * Constructs a <code>UpdateBinRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateBinRequest} obj Optional instance to populate.
     * @return {module:model/UpdateBinRequest} The populated <code>UpdateBinRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateBinRequest();

            if (data.hasOwnProperty('binID')) {
                obj['binID'] = ApiClient.convertToType(data['binID'], 'Number');
            }
            if (data.hasOwnProperty('binTypeID')) {
                obj['binTypeID'] = ApiClient.convertToType(data['binTypeID'], 'Number');
            }
            if (data.hasOwnProperty('binStatusID')) {
                obj['binStatusID'] = ApiClient.convertToType(data['binStatusID'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Bin identifier
 * @member {Number} binID
 */
UpdateBinRequest.prototype['binID'] = undefined;

/**
 * New Bin's Type ID
 * @member {Number} binTypeID
 */
UpdateBinRequest.prototype['binTypeID'] = undefined;

/**
 * New Bin's Status ID
 * @member {Number} binStatusID
 */
UpdateBinRequest.prototype['binStatusID'] = undefined;






export default UpdateBinRequest;

