/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WaveSuggestionItem model module.
 * @module model/WaveSuggestionItem
 * @version 5.0
 */
class WaveSuggestionItem {
    /**
     * Constructs a new <code>WaveSuggestionItem</code>.
     * A suggestion of where to add an item to a pick wave.
     * @alias module:model/WaveSuggestionItem
     * @param binName {String} Bin Name
     */
    constructor(binName) { 
        
        WaveSuggestionItem.initialize(this, binName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, binName) { 
        obj['binName'] = binName;
    }

    /**
     * Constructs a <code>WaveSuggestionItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WaveSuggestionItem} obj Optional instance to populate.
     * @return {module:model/WaveSuggestionItem} The populated <code>WaveSuggestionItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WaveSuggestionItem();

            if (data.hasOwnProperty('binName')) {
                obj['binName'] = ApiClient.convertToType(data['binName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Bin Name
 * @member {String} binName
 */
WaveSuggestionItem.prototype['binName'] = undefined;






export default WaveSuggestionItem;

