/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WaveSuggestionItem from './WaveSuggestionItem';

/**
 * The WaveSuggestionShipment model module.
 * @module model/WaveSuggestionShipment
 * @version 5.0
 */
class WaveSuggestionShipment {
    /**
     * Constructs a new <code>WaveSuggestionShipment</code>.
     * A suggested shipment to put into a pick wave
     * @alias module:model/WaveSuggestionShipment
     */
    constructor() { 
        
        WaveSuggestionShipment.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WaveSuggestionShipment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WaveSuggestionShipment} obj Optional instance to populate.
     * @return {module:model/WaveSuggestionShipment} The populated <code>WaveSuggestionShipment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WaveSuggestionShipment();

            if (data.hasOwnProperty('orderID')) {
                obj['orderID'] = ApiClient.convertToType(data['orderID'], 'Number');
            }
            if (data.hasOwnProperty('shipmentID')) {
                obj['shipmentID'] = ApiClient.convertToType(data['shipmentID'], 'Number');
            }
            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [WaveSuggestionItem]);
            }
        }
        return obj;
    }


}

/**
 * Order Identifier
 * @member {Number} orderID
 */
WaveSuggestionShipment.prototype['orderID'] = undefined;

/**
 * Shipment Identifier
 * @member {Number} shipmentID
 */
WaveSuggestionShipment.prototype['shipmentID'] = undefined;

/**
 * List of suggested items to put in shipment in a wave.
 * @member {Array.<module:model/WaveSuggestionItem>} items
 */
WaveSuggestionShipment.prototype['items'] = undefined;






export default WaveSuggestionShipment;

