/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Inventory);
  }
}(this, function(expect, Inventory) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Inventory.AggregateRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AggregateRequest', function() {
    it('should create an instance of AggregateRequest', function() {
      // uncomment below and update the code to test AggregateRequest
      //var instane = new Inventory.AggregateRequest();
      //expect(instance).to.be.a(Inventory.AggregateRequest);
    });

    it('should have the property items (base name: "items")', function() {
      // uncomment below and update the code to test the property items
      //var instane = new Inventory.AggregateRequest();
      //expect(instance).to.be();
    });

    it('should have the property ignoreSafetyStock (base name: "ignoreSafetyStock")', function() {
      // uncomment below and update the code to test the property ignoreSafetyStock
      //var instane = new Inventory.AggregateRequest();
      //expect(instance).to.be();
    });

    it('should have the property includeNegativeInventory (base name: "includeNegativeInventory")', function() {
      // uncomment below and update the code to test the property includeNegativeInventory
      //var instane = new Inventory.AggregateRequest();
      //expect(instance).to.be();
    });

    it('should have the property directShip (base name: "directShip")', function() {
      // uncomment below and update the code to test the property directShip
      //var instane = new Inventory.AggregateRequest();
      //expect(instance).to.be();
    });

    it('should have the property transferEnabled (base name: "transferEnabled")', function() {
      // uncomment below and update the code to test the property transferEnabled
      //var instane = new Inventory.AggregateRequest();
      //expect(instance).to.be();
    });

    it('should have the property pickup (base name: "pickup")', function() {
      // uncomment below and update the code to test the property pickup
      //var instane = new Inventory.AggregateRequest();
      //expect(instance).to.be();
    });

  });

}));
