/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Inventory);
  }
}(this, function(expect, Inventory) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Inventory.Bin();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Bin', function() {
    it('should create an instance of Bin', function() {
      // uncomment below and update the code to test Bin
      //var instane = new Inventory.Bin();
      //expect(instance).to.be.a(Inventory.Bin);
    });

    it('should have the property success (base name: "success")', function() {
      // uncomment below and update the code to test the property success
      //var instane = new Inventory.Bin();
      //expect(instance).to.be();
    });

    it('should have the property messages (base name: "messages")', function() {
      // uncomment below and update the code to test the property messages
      //var instane = new Inventory.Bin();
      //expect(instance).to.be();
    });

    it('should have the property numResults (base name: "numResults")', function() {
      // uncomment below and update the code to test the property numResults
      //var instane = new Inventory.Bin();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Inventory.Bin();
      //expect(instance).to.be();
    });

    it('should have the property binID (base name: "binID")', function() {
      // uncomment below and update the code to test the property binID
      //var instane = new Inventory.Bin();
      //expect(instance).to.be();
    });

    it('should have the property locationCode (base name: "locationCode")', function() {
      // uncomment below and update the code to test the property locationCode
      //var instane = new Inventory.Bin();
      //expect(instance).to.be();
    });

    it('should have the property binTypeID (base name: "binTypeID")', function() {
      // uncomment below and update the code to test the property binTypeID
      //var instane = new Inventory.Bin();
      //expect(instance).to.be();
    });

    it('should have the property binStatusID (base name: "binStatusID")', function() {
      // uncomment below and update the code to test the property binStatusID
      //var instane = new Inventory.Bin();
      //expect(instance).to.be();
    });

  });

}));
