/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Inventory);
  }
}(this, function(expect, Inventory) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Inventory.GetPendingItemsResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetPendingItemsResponse', function() {
    it('should create an instance of GetPendingItemsResponse', function() {
      // uncomment below and update the code to test GetPendingItemsResponse
      //var instane = new Inventory.GetPendingItemsResponse();
      //expect(instance).to.be.a(Inventory.GetPendingItemsResponse);
    });

    it('should have the property totalCount (base name: "totalCount")', function() {
      // uncomment below and update the code to test the property totalCount
      //var instane = new Inventory.GetPendingItemsResponse();
      //expect(instance).to.be();
    });

    it('should have the property page (base name: "page")', function() {
      // uncomment below and update the code to test the property page
      //var instane = new Inventory.GetPendingItemsResponse();
      //expect(instance).to.be();
    });

    it('should have the property perPage (base name: "perPage")', function() {
      // uncomment below and update the code to test the property perPage
      //var instane = new Inventory.GetPendingItemsResponse();
      //expect(instance).to.be();
    });

    it('should have the property prevPage (base name: "prevPage")', function() {
      // uncomment below and update the code to test the property prevPage
      //var instane = new Inventory.GetPendingItemsResponse();
      //expect(instance).to.be();
    });

    it('should have the property sortBy (base name: "sortBy")', function() {
      // uncomment below and update the code to test the property sortBy
      //var instane = new Inventory.GetPendingItemsResponse();
      //expect(instance).to.be();
    });

    it('should have the property sortAscending (base name: "sortAscending")', function() {
      // uncomment below and update the code to test the property sortAscending
      //var instane = new Inventory.GetPendingItemsResponse();
      //expect(instance).to.be();
    });

    it('should have the property pendingItems (base name: "pendingItems")', function() {
      // uncomment below and update the code to test the property pendingItems
      //var instane = new Inventory.GetPendingItemsResponse();
      //expect(instance).to.be();
    });

  });

}));
