/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Inventory);
  }
}(this, function(expect, Inventory) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Inventory.InventoryRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InventoryRequest', function() {
    it('should create an instance of InventoryRequest', function() {
      // uncomment below and update the code to test InventoryRequest
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be.a(Inventory.InventoryRequest);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property items (base name: "items")', function() {
      // uncomment below and update the code to test the property items
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property requestLocation (base name: "requestLocation")', function() {
      // uncomment below and update the code to test the property requestLocation
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property limit (base name: "limit")', function() {
      // uncomment below and update the code to test the property limit
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property locationWhitelist (base name: "locationWhitelist")', function() {
      // uncomment below and update the code to test the property locationWhitelist
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property locationPriorityList (base name: "locationPriorityList")', function() {
      // uncomment below and update the code to test the property locationPriorityList
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property locationBlacklist (base name: "locationBlacklist")', function() {
      // uncomment below and update the code to test the property locationBlacklist
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property ignoreSafetyStock (base name: "ignoreSafetyStock")', function() {
      // uncomment below and update the code to test the property ignoreSafetyStock
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property includeNegativeInventory (base name: "includeNegativeInventory")', function() {
      // uncomment below and update the code to test the property includeNegativeInventory
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property directShip (base name: "directShip")', function() {
      // uncomment below and update the code to test the property directShip
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property transferEnabled (base name: "transferEnabled")', function() {
      // uncomment below and update the code to test the property transferEnabled
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property pickup (base name: "pickup")', function() {
      // uncomment below and update the code to test the property pickup
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property includeInAggregateExport (base name: "includeInAggregateExport")', function() {
      // uncomment below and update the code to test the property includeInAggregateExport
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property includeInLocationExport (base name: "includeInLocationExport")', function() {
      // uncomment below and update the code to test the property includeInLocationExport
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property excludeBlockedAssignment (base name: "excludeBlockedAssignment")', function() {
      // uncomment below and update the code to test the property excludeBlockedAssignment
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property includeAttributes (base name: "includeAttributes")', function() {
      // uncomment below and update the code to test the property includeAttributes
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

    it('should have the property sortByEnum (base name: "sortByEnum")', function() {
      // uncomment below and update the code to test the property sortByEnum
      //var instane = new Inventory.InventoryRequest();
      //expect(instance).to.be();
    });

  });

}));
