/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Inventory);
  }
}(this, function(expect, Inventory) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Inventory.JobQueueResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JobQueueResponse', function() {
    it('should create an instance of JobQueueResponse', function() {
      // uncomment below and update the code to test JobQueueResponse
      //var instane = new Inventory.JobQueueResponse();
      //expect(instance).to.be.a(Inventory.JobQueueResponse);
    });

    it('should have the property jobID (base name: "jobID")', function() {
      // uncomment below and update the code to test the property jobID
      //var instane = new Inventory.JobQueueResponse();
      //expect(instance).to.be();
    });

    it('should have the property tenantID (base name: "tenantID")', function() {
      // uncomment below and update the code to test the property tenantID
      //var instane = new Inventory.JobQueueResponse();
      //expect(instance).to.be();
    });

    it('should have the property locationID (base name: "locationID")', function() {
      // uncomment below and update the code to test the property locationID
      //var instane = new Inventory.JobQueueResponse();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new Inventory.JobQueueResponse();
      //expect(instance).to.be();
    });

    it('should have the property added (base name: "added")', function() {
      // uncomment below and update the code to test the property added
      //var instane = new Inventory.JobQueueResponse();
      //expect(instance).to.be();
    });

    it('should have the property started (base name: "started")', function() {
      // uncomment below and update the code to test the property started
      //var instane = new Inventory.JobQueueResponse();
      //expect(instance).to.be();
    });

    it('should have the property finished (base name: "finished")', function() {
      // uncomment below and update the code to test the property finished
      //var instane = new Inventory.JobQueueResponse();
      //expect(instance).to.be();
    });

    it('should have the property originalFilename (base name: "originalFilename")', function() {
      // uncomment below and update the code to test the property originalFilename
      //var instane = new Inventory.JobQueueResponse();
      //expect(instance).to.be();
    });

    it('should have the property hasData (base name: "hasData")', function() {
      // uncomment below and update the code to test the property hasData
      //var instane = new Inventory.JobQueueResponse();
      //expect(instance).to.be();
    });

    it('should have the property itemCount (base name: "itemCount")', function() {
      // uncomment below and update the code to test the property itemCount
      //var instane = new Inventory.JobQueueResponse();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new Inventory.JobQueueResponse();
      //expect(instance).to.be();
    });

  });

}));
