/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Inventory);
  }
}(this, function(expect, Inventory) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Inventory.MDeleteItem();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MDeleteItem', function() {
    it('should create an instance of MDeleteItem', function() {
      // uncomment below and update the code to test MDeleteItem
      //var instane = new Inventory.MDeleteItem();
      //expect(instance).to.be.a(Inventory.MDeleteItem);
    });

    it('should have the property productID (base name: "productID")', function() {
      // uncomment below and update the code to test the property productID
      //var instane = new Inventory.MDeleteItem();
      //expect(instance).to.be();
    });

    it('should have the property inventoryIDs (base name: "inventoryIDs")', function() {
      // uncomment below and update the code to test the property inventoryIDs
      //var instane = new Inventory.MDeleteItem();
      //expect(instance).to.be();
    });

    it('should have the property locationIDs (base name: "locationIDs")', function() {
      // uncomment below and update the code to test the property locationIDs
      //var instane = new Inventory.MDeleteItem();
      //expect(instance).to.be();
    });

    it('should have the property auditIDs (base name: "auditIDs")', function() {
      // uncomment below and update the code to test the property auditIDs
      //var instane = new Inventory.MDeleteItem();
      //expect(instance).to.be();
    });

    it('should have the property pickWaveIDs (base name: "pickWaveIDs")', function() {
      // uncomment below and update the code to test the property pickWaveIDs
      //var instane = new Inventory.MDeleteItem();
      //expect(instance).to.be();
    });

    it('should have the property itemIdentifier (base name: "itemIdentifier")', function() {
      // uncomment below and update the code to test the property itemIdentifier
      //var instane = new Inventory.MDeleteItem();
      //expect(instance).to.be();
    });

  });

}));
