/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Inventory);
  }
}(this, function(expect, Inventory) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Inventory.OrderItemInformation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrderItemInformation', function() {
    it('should create an instance of OrderItemInformation', function() {
      // uncomment below and update the code to test OrderItemInformation
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be.a(Inventory.OrderItemInformation);
    });

    it('should have the property orderID (base name: "orderID")', function() {
      // uncomment below and update the code to test the property orderID
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property orderItemID (base name: "orderItemID")', function() {
      // uncomment below and update the code to test the property orderItemID
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property locationID (base name: "locationID")', function() {
      // uncomment below and update the code to test the property locationID
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property locationActive (base name: "locationActive")', function() {
      // uncomment below and update the code to test the property locationActive
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property locationCode (base name: "locationCode")', function() {
      // uncomment below and update the code to test the property locationCode
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property locationName (base name: "locationName")', function() {
      // uncomment below and update the code to test the property locationName
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property binID (base name: "binID")', function() {
      // uncomment below and update the code to test the property binID
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property partNumber (base name: "partNumber")', function() {
      // uncomment below and update the code to test the property partNumber
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property upc (base name: "upc")', function() {
      // uncomment below and update the code to test the property upc
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property sku (base name: "sku")', function() {
      // uncomment below and update the code to test the property sku
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property ltd (base name: "ltd")', function() {
      // uncomment below and update the code to test the property ltd
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property floor (base name: "floor")', function() {
      // uncomment below and update the code to test the property floor
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property safetyStock (base name: "safetyStock")', function() {
      // uncomment below and update the code to test the property safetyStock
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property onHand (base name: "onHand")', function() {
      // uncomment below and update the code to test the property onHand
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property available (base name: "available")', function() {
      // uncomment below and update the code to test the property available
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property allocated (base name: "allocated")', function() {
      // uncomment below and update the code to test the property allocated
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property allocates (base name: "allocates")', function() {
      // uncomment below and update the code to test the property allocates
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property deallocates (base name: "deallocates")', function() {
      // uncomment below and update the code to test the property deallocates
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property fulfills (base name: "fulfills")', function() {
      // uncomment below and update the code to test the property fulfills
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property picks (base name: "picks")', function() {
      // uncomment below and update the code to test the property picks
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property pendingQuantity (base name: "pendingQuantity")', function() {
      // uncomment below and update the code to test the property pendingQuantity
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

    it('should have the property events (base name: "events")', function() {
      // uncomment below and update the code to test the property events
      //var instane = new Inventory.OrderItemInformation();
      //expect(instance).to.be();
    });

  });

}));
