/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Inventory);
  }
}(this, function(expect, Inventory) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Inventory.ProductQuantity();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductQuantity', function() {
    it('should create an instance of ProductQuantity', function() {
      // uncomment below and update the code to test ProductQuantity
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be.a(Inventory.ProductQuantity);
    });

    it('should have the property partNumber (base name: "partNumber")', function() {
      // uncomment below and update the code to test the property partNumber
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property upc (base name: "upc")', function() {
      // uncomment below and update the code to test the property upc
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property sku (base name: "sku")', function() {
      // uncomment below and update the code to test the property sku
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property quantity (base name: "quantity")', function() {
      // uncomment below and update the code to test the property quantity
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property binID (base name: "binID")', function() {
      // uncomment below and update the code to test the property binID
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property locationID (base name: "locationID")', function() {
      // uncomment below and update the code to test the property locationID
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property binTypeID (base name: "binTypeID")', function() {
      // uncomment below and update the code to test the property binTypeID
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property binStatusID (base name: "binStatusID")', function() {
      // uncomment below and update the code to test the property binStatusID
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property inventoryID (base name: "inventoryID")', function() {
      // uncomment below and update the code to test the property inventoryID
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property tenantLocProductID (base name: "tenantLocProductID")', function() {
      // uncomment below and update the code to test the property tenantLocProductID
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property auditProductID (base name: "auditProductID")', function() {
      // uncomment below and update the code to test the property auditProductID
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property auditID (base name: "auditID")', function() {
      // uncomment below and update the code to test the property auditID
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property onHand (base name: "onHand")', function() {
      // uncomment below and update the code to test the property onHand
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property available (base name: "available")', function() {
      // uncomment below and update the code to test the property available
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property allocated (base name: "allocated")', function() {
      // uncomment below and update the code to test the property allocated
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property pending (base name: "pending")', function() {
      // uncomment below and update the code to test the property pending
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property ltd (base name: "ltd")', function() {
      // uncomment below and update the code to test the property ltd
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property floor (base name: "floor")', function() {
      // uncomment below and update the code to test the property floor
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

    it('should have the property safetystock (base name: "safetystock")', function() {
      // uncomment below and update the code to test the property safetystock
      //var instane = new Inventory.ProductQuantity();
      //expect(instance).to.be();
    });

  });

}));
