/**
 * Inventory
 * Swagger JSON for inventory apis
 *
 * The version of the OpenAPI document: 5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Inventory);
  }
}(this, function(expect, Inventory) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Inventory.WaveControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('WaveControllerApi', function() {
    describe('closePickWave', function() {
      it('should call closePickWave successfully', function(done) {
        //uncomment below and update the code to test closePickWave
        //instance.closePickWave(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createPickWave', function() {
      it('should call createPickWave successfully', function(done) {
        //uncomment below and update the code to test createPickWave
        //instance.createPickWave(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOpenPickWaves', function() {
      it('should call getOpenPickWaves successfully', function(done) {
        //uncomment below and update the code to test getOpenPickWaves
        //instance.getOpenPickWaves(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getWaveDetails', function() {
      it('should call getWaveDetails successfully', function(done) {
        //uncomment below and update the code to test getWaveDetails
        //instance.getWaveDetails(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('queryWaveSuggestion', function() {
      it('should call queryWaveSuggestion successfully', function(done) {
        //uncomment below and update the code to test queryWaveSuggestion
        //instance.queryWaveSuggestion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
